### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by patelhiren** [jamesdunay/MinimalTabBar#4]
Hey,

This looks like a very good implementation. I am trying to see how to get this working. Downloaded the example and also ran pod install. Seems there are some layout issues. I am using iPhone 6 running iOS 8.1.2. The tab icons show up when I tap the bottom right but not always and the view controllers don't render at all. The viewdidload is firing for the view controllers.

Can you please share your example code? The one you have committed currently doesn't show how to use the MinimalTabBar.

Thanks

**Comment by jamesdunay** [comment]
Hey Hiren,

You bet! I'll take a look sometime this afternoon and get back to you.
- James

**Comment by jamesdunay** [comment]
We're you using the MinimalTabBarDemo repo? If not which branch are you on in MinimalTabBar?

**Comment by patelhiren** [comment]
I just cloned the master branch from 'https://github.com/jamesdunay/MinimalTabBar.git'

**Comment by jamesdunay** [comment]
gotcha, ya I had some leftover code that was auto-generated when making the cocoapod. I'm attempting to keep this repo as POD focused as possible so I've created a separate branch to showcase a full demo. It's linked in the ReadMe/Description but here it is as well.  https://github.com/jamesdunay/MinimalTabBarDemo

Let me know if you have any issues. Thanks

**Comment by jamesdunay** [comment]
Also take a look at 0.1.2, should be the default branch

**Comment by patelhiren** [comment]
Ah that works great. I am able to see a functioning demo. That should help me get it going. Thanks so much.
